### ISSUE TITLE
Syntax update causing issue with extractVars()

### ISSUE THREAD

**Issue by thomasbattram** [explodecomputer/alspac#2]
There are some core variables (e.g. kz011b) which are present in the ALSPAC data multiple times, I suspect this is because of some recent syntax updates. This causes an issue when running `extractVars()` because these core variables are filtered on during the process, so the result of running the following

``` R
data(current)
result <- extractVars(current[3, ], core_only = TRUE) # core_only = TRUE is the default
```

is a completely empty result file. Here are the warning messages:

```
New names:
• `in_alsp` -> `in_alsp...24`
• `in_core` -> `in_core...25`
• `in_phase2` -> `in_phase2...26`
• `in_phase3` -> `in_phase3...27`
• `in_phase4` -> `in_phase4...28`
• `tripquad` -> `tripquad...29`
• `kz011b` -> `kz011b...30`
• `kz021` -> `kz021...31`
• `in_obj_cp` -> `in_obj_cp...32`
• `in_alsp` -> `in_alsp...33`
• `in_core` -> `in_core...34`
• `in_phase2` -> `in_phase2...35`
• `in_phase3` -> `in_phase3...36`
• `in_phase4` -> `in_phase4...37`
• `tripquad` -> `tripquad...38`
• `kz021` -> `kz021...39`
• `kz011b` -> `kz011b...40`
• `in_obj_cp` -> `in_obj_cp...41`
New names:
• `in_alsp...24` -> `in_alsp...11`
• `in_core...25` -> `in_core...12`
• `in_phase2...26` -> `in_phase2...13`
• `in_phase3...27` -> `in_phase3...14`
• `in_phase4...28` -> `in_phase4...15`
• `tripquad...29` -> `tripquad...16`
• `kz011b...30` -> `kz011b...17`
• `kz021...31` -> `kz021...18`
• `in_cp...32` -> `in_cp...19`
• `in_alsp...33` -> `in_alsp...20`
• `in_core...34` -> `in_core...21`
• `in_phase2...35` -> `in_phase2...22`
• `in_phase3...36` -> `in_phase3...23`
• `in_phase4...37` -> `in_phase4...24`
• `tripquad...38` -> `tripquad...25`
• `kz021...39` -> `kz021...26`
• `kz011b...40` -> `kz011b...27`
• `in_cp...41` -> `in_cp...28`
Automatically removing data for individuals who have withdrawn consent.
Warning messages:
1: In FUN(X[[i]], ...) : Filter for kz011b matches multiple variables
2: In FUN(X[[i]], ...) : Filter for kz021 matches multiple variables
3: In FUN(X[[i]], ...) : Filter for tripquad matches multiple variables
4: In FUN(X[[i]], ...) : Filter for in_core matches multiple variables
5: In FUN(X[[i]], ...) : Filter for in_alsp matches multiple variables
6: In FUN(X[[i]], ...) : Filter for in_phase2 matches multiple variables
7: In FUN(X[[i]], ...) : Filter for in_phase3 matches multiple variables
8: In FUN(X[[i]], ...) : Filter for in_phase4 matches multiple variables
```

``` R
sessionInfo()
```

```
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS  10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
[1] alspac_0.36.0      dplyr_1.0.9        plyr_1.8.7         stringr_1.4.0
[5] haven_2.5.0        readstata13_0.10.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9       magrittr_2.0.3   hms_1.1.1        tidyselect_1.1.2
 [5] R6_2.5.1         rlang_1.0.4      fansi_1.0.3      tools_4.0.2
 [9] utf8_1.2.2       cli_3.3.0        DBI_1.1.1        ellipsis_0.3.2
[13] assertthat_0.2.1 tibble_3.1.8     lifecycle_1.0.1  purrr_0.3.4
[17] vctrs_0.4.1      glue_1.6.2       stringi_1.7.8    compiler_4.0.2
[21] pillar_1.8.0     forcats_0.5.1    generics_0.1.3   pkgconfig_2.0.3
```

**Comment by explodecomputer** [comment]
Thanks @thomasbattram 
@perishky - do you think the way to fix this is to intercept here https://github.com/explodecomputer/alspac/blob/master/R/dictionary.r#L114 and use `union` instead of `bind_rows`? It will drop the subsequent rows that are repeated above I think. However all the values would need to be identical in the row. Alternative to just one by one check if each data frame duplicates rows in previous one and drop those rows before binding. Just asking cos i'm not sure what the data implications are i.e. if someone wants the row from the dataset where the rows have been removed then how do they know where to find it.

**Comment by perishky** [comment]
This is due to an ALSPAC update where they didn't move some old versions of files to the archive, in particular:
- COVID5_G0Dad_2a.dta was added, but COVID5_G0Partner_1a.dta not moved
- COVID5_Mum_2a.dta was added, but COVID5_Mum_1a.dta not moved
- COVID5_YP_2a.dta was added, but  COVID5_YP_1a.dta was not moved
- FOM2_4b.dta incorrectly includes a variable fm1a011 (which is correctly also found in FOM1_3c.dta)
- Current/Other/Sample Definition/cp_3a.dta was added, but Current/Other/Cohort Profile/cp_2b.dta not moved
- kz_5c.dta and cp_3a.dta contain several of the same kz* variables, but for slightly different numbers of individuals.
I'll let ALSPAC know about this.  This should be corrected before we should consider changing the R package.

**Comment by perishky** [comment]
@thomasbattram 
I think it's fixed now, just by having removed the files meant for archiving.  Could you give it another try?  You shouldn't have to update any dictionaries because I've just updated them.
